FROM eclipse-temurin:17-jdk
WORKDIR /workspace

# Copy project and run tests
COPY . /workspace

# Grant execute permission to gradlew
RUN chmod +x gradlew

# Pre-build to download dependencies
RUN ./gradlew --no-daemon -x test build

CMD ["./gradlew", "--no-daemon", "test"]
